
product:
  url: "https://redsky.target.com/v2/pdp/tcin/{id}?excludes=taxonomy,price,promtion,bulk_ship,rating_and_review_reviews,rating_and_review_statistics,question_and_answer_statistics"

logging:
  level:
    root: WARN
    org.springframework.web.client: DEBUG